"""initial schema

Revision ID: 66766e088730
Revises: 
Create Date: 2026-09-21 12:18:23.742734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66766e088730'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('line_channel_id', sa.String(length=64), nullable=True),
    sa.Column('line_channel_secret_enc', sa.LargeBinary(), nullable=False),
    sa.Column('line_channel_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('line_destination', sa.String(length=64), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=64), nullable=False),
    sa.Column('forbidden_phrases', sa.JSON(), nullable=False),
    sa.Column('fallback_message', sa.Text(), nullable=False),
    sa.Column('human_mode_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('vector_collection', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_companies_line_destination'), 'companies', ['line_destination'], unique=True)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('vector_collection', sa.String(length=128), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'READY', 'FAILED', name='documentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'checksum', name='uq_doc_company_checksum')
    )
    op.create_index('ix_doc_company_status', 'knowledge_documents', ['company_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.Enum('AI', 'HUMAN', name='conversationmode', native_enum=False, length=8), nullable=False),
    sa.Column('mode_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'line_user_id', name='uq_users_company_line_user')
    )
    op.create_index('ix_users_company_mode', 'users', ['company_id', 'mode'], unique=False)
    op.create_index(op.f('ix_users_mode_expires_at'), 'users', ['mode_expires_at'], unique=False)
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'HUMAN_AGENT', name='chatrole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('line_message_id', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_message_id', name='uq_chat_line_message_id')
    )
    op.create_index(op.f('ix_chat_histories_company_id'), 'chat_histories', ['company_id'], unique=False)
    op.create_index('ix_chat_user_created', 'chat_histories', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_user_created', table_name='chat_histories')
    op.drop_index(op.f('ix_chat_histories_company_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    op.drop_index(op.f('ix_users_mode_expires_at'), table_name='users')
    op.drop_index('ix_users_company_mode', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_doc_company_status', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_companies_line_destination'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
